config/routes.rb
Rails.application.routes.draw do
  resources :applications
  devise_for :users, :path => 'u', :controllers => { registrations: 'registrations' , omniauth_callbacks: "omniauth_callbacks"}
  resources :users, :only => [:index, :new, :create, :destroy]
  get 'application_tracking_system/home'
  get 'application_tracking_system/help'
  get 'application_tracking_system/menu'
  # match '/users', to: 'users#index', via: 'get'
  get '/users', to: 'users#new'
  match '/users/new', to: 'users#new', via: 'get'
  match '/users', to: 'users#create', via: 'post'
  # match '/users/:id', to: 'users#remove', via: 'delete'
  resources :application_tracking_system
  resources :jobs
  resources :companies
  resources :searches, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application_tracking_system#home'
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :applications
  validates :company_id, presence: true
  validates :job_description, presence: true
  validates :employment_type, presence: true
  validates :responsibilities, presence: true
  validates :requirements, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    if user_signed_in? && current_user.is_applicant
      respond_to do |format|
        format.html { redirect_to application_tracking_system_menu_url }
      end
    end
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    if user_signed_in? && current_user.is_applicant
      respond_to do |format|
        format.html { redirect_to application_tracking_system_menu_url }
      end
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @application = Application.where(job_id: @job.id)
    @application.destroy_all
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company_id, :recruiter_id, :job_status, :job_description, :employment_type, :responsibilities, :requirements)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :recruiter_id, :value => current_user.id %>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.select :company_id, options_for_select(Company.select(:name,:id).where(id: current_user.company_id).collect{|c| [c.name,c.id]}) %><br/>


  </div>

  <div class="field">
    <%= form.label :job_description %>
    <%= form.text_area :job_description, id: :job_job_description %>
  </div>

  <div class="field">
    <%= form.label :employment_type %>
    <%= form.select :employment_type, options_for_select(['Full-Time', 'Part-Time', 'Internship', 'Contractor']) %>
  </div>

  <div class="field">
    <%= form.label :responsibilities %>
    <%= form.text_area :responsibilities, id: :job_responsibilities %>
  </div>

  <div class="field">
    <%= form.label :requirements %>
    <%= form.text_area :requirements, id: :job_requirements %>
  </div>

  <div class="field">
    <%= form.label :job_status %>
    <%= form.select :job_status, options_for_select(["Open", "Closed"], "Open") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table class = "table table-bordered table-striped">
  <thead>
  <tr>
    <th>Company</th>
    <th>Job description</th>
    <th>Employment type</th>
    <th>Responsibilities</th>
    <th>Requirements</th>
    <th>Job Status</th>
    <th>Options</th>
  </tr>
  </thead>

  <tbody>
  <% @jobs.each do |job| %>
    <tr>
      <td><%= Company.find(job.company_id).name %></td>
      <td><%= job.job_description %></td>
      <td><%= job.employment_type %></td>
      <td><%= job.responsibilities %></td>
      <td><%= job.requirements %></td>
      <td><%= job.job_status %></td>
      <td><%= link_to 'Show', job %>
        <% if current_user.is_admin || (current_user.is_recruiter && current_user.id == job.recruiter_id)%>
          | <%= link_to 'Edit', edit_job_path(job) %>
        <% end %>
        <% if current_user.is_admin || (current_user.is_recruiter && current_user.company_id == job.company_id) %>
          | <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        <% if current_user.is_applicant && current_user.company_id != job.company_id && job.job_status != "Closed"%>
          | <%= link_to 'Apply', new_application_path(:job_id => job.id)%>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if current_user.is_recruiter? %>
  <% if current_user.company_id==nil %>
    <i style="color: #cc0000">Please add a company by <%= link_to "editing your profile", edit_user_registration_path %> to post jobs.</i>
  <%else%>
    <%= link_to 'New Job', new_job_path %><br><br>
  <%end%>
<%end%>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job.company_id %>
</p>

<p>
  <strong>Job description:</strong>
  <%= @job.job_description %>
</p>

<p>
  <strong>Employment type:</strong>
  <%= @job.employment_type %>
</p>

<p>
  <strong>Responsibilities:</strong>
  <%= @job.responsibilities %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @job.requirements %>
</p>

<p>
  <strong>Job Status:</strong>
  <%= @job.job_status %>
</p>

<% if current_user.is_applicant %>
  <%= link_to 'Apply!', new_application_path(:job_id => job.id) %> |
<% end %>
<% if current_user.is_recruiter %>
  <%= link_to 'Edit', edit_job_path(@job) %> |
<% end %>
<%= link_to 'Back', jobs_path %>