config/routes.rb
Rails.application.routes.draw do
  resources :applications
  devise_for :users, :path => 'u', :controllers => { registrations: 'registrations' , omniauth_callbacks: "omniauth_callbacks"}
  resources :users, :only => [:index, :new, :create, :destroy]
  get 'application_tracking_system/home'
  get 'application_tracking_system/help'
  get 'application_tracking_system/menu'
  # match '/users', to: 'users#index', via: 'get'
  get '/users', to: 'users#new'
  match '/users/new', to: 'users#new', via: 'get'
  match '/users', to: 'users#create', via: 'post'
  # match '/users/:id', to: 'users#remove', via: 'delete'
  resources :application_tracking_system
  resources :jobs
  resources :companies
  resources :searches, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application_tracking_system#home'
end

app/controllers/application_tracking_system_controller.rb
class ApplicationTrackingSystemController < ApplicationController
  def home
    if user_signed_in?
      respond_to do |format|
        format.html { redirect_to application_tracking_system_menu_url }
      end
    end
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up){|u| u.permit(:fname, :lname,:phone_no,:email,:password,:is_recruiter,:is_applicant)}
    devise_parameter_sanitizer.for(:account_update){|u| u.permit(:fname, :lname,:phone_no,:name,:email,:password,:current_password,:is_recruiter,:is_applicant)}
  end
  def help
  end
  def menu
  end
end

app/helpers/application_tracking_system_helper.rb
module ApplicationTrackingSystemHelper
end

app/views/application_tracking_system/help.html.erb
<% provide(:title, "Help") %>
<div class="center jumbotron" style="text-align: center; color: #730E15">
  <br/>
  <h2>
    This application was created with the intention to find you your dream job, or your dream candidate.
  </h2>
  <br/>

</div>

app/views/application_tracking_system/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron" style="text-align: center; color: #730E15">
  <br/>
  <h1>Application Tracking System</h1>
  <br/>
  <h2>
    Find your dream job, guaranteed!
  </h2>
  <br/>

  <%= link_to "Sign up now!",  new_user_registration_path , class: "btn btn-lg btn-primary"%>
  <br/><br/>
  <b>Already have an account?</b>
  <br/>
  <%= link_to "Login",  new_user_session_path , class: "btn btn-sm btn-primary"%>
</div>

app/views/application_tracking_system/menu.html.erb
<p id="notice"><%= notice %></p>

<% provide(:title, "Menu") %>

<div class="jumbotron" style="text-align: center">
  <h2>What would you like to do?</h2>
  <br/>

  <% if current_user.is_admin? %>
    <%= link_to "Create new user", users_new_path  , class: "btn btn-md btn-primary"%>
    <br/><br/>
    <%= link_to "View all users", users_url  , class: "btn btn-md btn-primary"%>
    <br/><br/>
  <% end %>

  <% if current_user.is_recruiter? %>
    <% if current_user.company_id==nil %>
      <i style="color: #cc0000">Please add a company by <%= link_to "editing your profile", edit_user_registration_path %> to post jobs.</i>
    <%else%>
      <%= link_to "Post new job", new_job_url  , class: "btn btn-md btn-primary"%>
    <% end %>
    <br/><br/>
  <% end %>

  <% if current_user.is_recruiter? || current_user.is_admin?%>
    <%= link_to "Create new company", new_company_url  , class: "btn btn-md btn-primary"%>
    <br/><br/>
    <%= link_to "View all applications", applications_url  , class: "btn btn-md btn-primary"%>
    <br/><br/>
  <%end%>

  <%= link_to "View all posted Jobs", jobs_url  , class: "btn btn-md btn-primary"%>
  <br/><br/>
  <%= link_to "Search jobs by filter", new_search_url  , class: "btn btn-md btn-primary"%>
  <br/><br/>
  <%= link_to "View all Companies", companies_path  , class: "btn btn-md btn-primary"%>
  <br/><br/>

  <% if current_user.is_applicant?%>
    <%= link_to "View jobs I have applied to", applications_url  , class: "btn btn-md btn-primary"%>
  <% end %>
</div>