config/routes.rb
Rails.application.routes.draw do
  resources :applications
  devise_for :users, :path => 'u', :controllers => { registrations: 'registrations' , omniauth_callbacks: "omniauth_callbacks"}
  resources :users, :only => [:index, :new, :create, :destroy]
  get 'application_tracking_system/home'
  get 'application_tracking_system/help'
  get 'application_tracking_system/menu'
  # match '/users', to: 'users#index', via: 'get'
  get '/users', to: 'users#new'
  match '/users/new', to: 'users#new', via: 'get'
  match '/users', to: 'users#create', via: 'post'
  # match '/users/:id', to: 'users#remove', via: 'delete'
  resources :application_tracking_system
  resources :jobs
  resources :companies
  resources :searches, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application_tracking_system#home'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <b class="headertext"><%= link_to "Application Tracking System", application_tracking_system_home_url , id: "logo" %></b>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <%= link_to "Home",   application_tracking_system_home_path %>
        <b class="headertext">|</b>
        <%= link_to "Help",   application_tracking_system_help_path %>

        <% if user_signed_in? %>
          <br/>
          <b class="headertext">Logged in as <strong><%= current_user.fname %></strong></b>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
          <b class="headertext">|</b>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <b class="headertext">|</b>
          <%= link_to "Log in", new_user_session_path %><
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  </head>

  <body>
  <div class="header">
  <%= render 'layouts/header' %>
  </div>
  <br>
  <br>
  <br>
  <div class="container" style="padding-top: 30px">

    <%= yield %>
  </div>
  </body>
</html>